@startuml
autonumber 0
participant "Пользователь" as Пользователь #yellow
participant "Админ" as Админ #yellow
participant "Система" as Система #white

== Создание проекта Админом ==

Админ -> Система: Запрос на регистрацию
note right
  Админ записывается в систему.
end note

Система -> Админ: Подтверждение регистрации

Админ -> Система: Запрос на вход в систему (Login)
note right
  Админу генерируются access и refresh токены.
end note

Система -> Админ: Ответ с токенами

Админ -> Система: Запрос на авторизацию с access токеном
Система -> Админ: Подтверждение авторизации и доступ к системе
note right
    Админу даются права на crud операции с проектами.
end note

Админ -> Система: Запрос на создание проекта
Система -> Админ: Подтверждение создания проекта

== Регистрация и Авторизация Пользователя ==

Пользователь -> Система: Регистрация на проект по идентификатору
note right
  Пользователь прикрепляется к проекту.
end note

Система -> Пользователь: Подтверждение регистрации

Пользователь -> Система: Запрос на вход в проект (Login)
note right
  Пользователю генерируются access и refresh токены.
end note
Система -> Пользователь: Ответ с токенами

Пользователь -> Система: Запрос на авторизацию в проекте
note right
  Пользователю дается ответ со временем жизни его access токена
end note
Система -> Пользователь: Ответ с объектом авторизации

@enduml
